default_name = 'unknown'
removing_record = 'Removing old record %s.'
invalid_database_data = 'Invalid Database data'
updating_weather_for_region = 'Updating weather for region %s.'
region_deleted_weather_delete = "Region %s was deleted. Removing its weather data."
weather_sunny = 'Sunny'
weather_sun = 'Sun'
weather_heat = 'Heat'
weather_soft_rain = 'Soft rain'
weather_moderate_rain = 'Moderate rain'
weather_torrential_rain = 'Torrential rain'
weather_soft_wind = 'Soft wind'
weather_moderate_wind = 'Moderate wind'
weather_torrential_wind = 'Torrential wind'
weather_soft_snow_fall = 'Soft snow fall'
weather_moderate_snow_fall = 'Moderate snow fall'
weather_massive_snow_fall = 'Massive snow fall'

checking_database = '\nChecking database content - %s\n' \
    '------------------------------------'
string_nothing_to_do = 'Nothing to do.'
